program:
  image: daocloud.io/yihuo/php55
  restart: always
  links:
  - db
  ports:
  - "80"
  environment:
  - VIRTUAL_HOST=wx.yihuonet.com
  volumes:
  - /data/wx.yihuonet.com/www:/var/www/html
db:
  image: daocloud.io/yihuo/mysql55
  restart: always
  expose:
  - "3306"
  volumes:
  - /data/wx.yihuonet.com/mysql:/var/lib/mysql
  labels:
  - "All settings define in yihuo/mysql55 image"
  - "MySQL-Server:db"
  - "MySQL-Database:db"
  - "MySQL-User:dbuser"
  - "MySQL-User-Passwd:dbpasswd"
