program:
  image: daocloud.io/yihuo/wx_yihuonet_com
  restart: always
  links:
  - db
  ports:
  - '8080'
  environment:
  - YIHUONET_MCMS_MYSQL_USER=dbuser
  - YIHUONET_MCMS_MYSQL_USER_PASS=dbpasswd
  - VIRTUAL_HOST=wx.yihuonet.com
  - YIHUONET_MCMS_MYSQL_JDBC=jdbc:mysql://db:3306/db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
db:
  image: daocloud.io/yihuo/mysql55
  restart: always
  expose:
  - '3306'
